### ISSUE TITLE
login post request

### ISSUE THREAD

**Issue by beeguy1234** [nyxnyx/onstar#1]
This is a great project nyxnyx and just what I'm looking for for my personal home automation. 
It works fine for my opel.
I'm trying to transpose this to node.js, but am getting only '401 Unauthorized' responses on login.  (Same with curl and other clients.)  
The login looks like a simple post request of the payload object.  Do you see any reason it works through aiohttp.ClientSession but not through other clients ?
Thank you.

**Comment by nyxnyx** [comment]
Not sure why node.js isn't working - maybe some headers? Cookies? I can't help you with that.
