### ISSUE TITLE
How to get it working

### ISSUE THREAD

**Issue by elRadix** [nyxnyx/onstar#3]
I  am just starting with onstar to get this working in Home-Assistant.
Can you tell how to run these commands ?

getting some errors:
```
python demo.py 
  File "demo.py", line 25
    response = yield from session.post('https://gsp.eur.onstar.com/gspserver/services/admin/login.json', data=payload) 
                        ^
SyntaxError: invalid syntax

```

**Comment by cyberlecgui** [comment]
> I am just starting with onstar to get this working in Home-Assistant.
> Can you tell how to run these commands ?
> 
> getting some errors:
> 
> ```
> python demo.py 
>   File "demo.py", line 25
>     response = yield from session.post('https://gsp.eur.onstar.com/gspserver/services/admin/login.json', data=payload) 
>                         ^
> SyntaxError: invalid syntax
> ```
1st : you have to install python 36 and then you have to install the module aiohttp and then it should works perfectly !

**Comment by cyberlecgui** [comment]
Hi all !
I have a small problem, in the JSON File the root folder is named "Results" for diags and also for location.
It is possible to name for example "Results" as "ResultsDiags" and "ResultsLocation" ? 
Then I can generate just one Json file every minutes to get one by my domotic system.

Regards
Guillaume

**Comment by nyxnyx** [comment]
please use python3
